import os
import json
import logging
from models import db, Journey, JourneyStep, StepDependency
from services.llm_service import LLMService

logger = logging.getLogger(__name__)

class PlannerService:
    @staticmethod
    def _load_bakery_template():
        """Load the structured bakery template from the knowledge module."""
        try:
            # Locate bakery_template.json inside backend/knowledge/
            current_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
            template_path = os.path.join(current_dir, 'knowledge', 'bakery_template.json')
            
            with open(template_path, 'r', encoding='utf-8') as f:
                return json.load(f)
        except Exception as e:
            logger.error(f"Failed to load bakery template JSON: {e}")
            raise RuntimeError("Knowledge base bakery template not found or corrupt.")

    @classmethod
    def plan_journey(cls, goal_text):
        """
        Builds a new Journey DAG in the database from the user's goal.
        Resolves initial step locks and sets up database dependencies.
        """
        # Call consolidated LLMService to plan journey details in a single roundtrip
        logger.info(f"Invoking consolidated LLM Service for goal: '{goal_text}'")
        llm_details = LLMService.plan_journey_details(goal_text)
        
        # Route to static bakery template or use dynamic steps generated by the LLM
        if llm_details.get('is_bakery_intent', False):
            logger.info("Goal matched Bakery intent. Loading static bakery knowledge template.")
            template = cls._load_bakery_template()
        else:
            logger.info("Goal does not match Bakery intent. Using dynamically planned steps.")
            template = {"steps": llm_details.get('steps', [])}
        
        # 1. Create the Journey container with LLM analysis metadata
        journey = Journey(
            goal_text=goal_text, 
            status='READY',
            metadata_json={
                'risk_analysis': llm_details.get('risk_analysis', ''),
                'custom_advice': llm_details.get('custom_advice', '')
            }
        )
        db.session.add(journey)
        db.session.flush() # Populate journey.id
        
        # 2. Scaffolding steps in the database
        template_steps = template.get('steps', [])
        db_steps = {} # Map template_step_id -> JourneyStep instance
        
        for index, t_step in enumerate(template_steps):
            # Initial status: PENDING if it has no dependencies, LOCKED otherwise
            has_deps = len(t_step.get('dependencies', [])) > 0
            initial_status = 'LOCKED' if has_deps else 'PENDING'
            
            step = JourneyStep(
                journey_id=journey.id,
                template_step_id=t_step['id'],
                title=t_step['title'],
                description=t_step.get('description'),
                department=t_step.get('department'),
                authority=t_step.get('authority'),
                estimated_time=t_step.get('estimated_time', 1),
                status=initial_status,
                sequence_order=index,
                documents=t_step.get('documents', []),
                metadata_json={}
            )
            db.session.add(step)
            db_steps[t_step['id']] = step
            
        db.session.flush() # Populate all step.id fields
        
        # 3. Resolve dependencies and create StepDependency records
        for t_step in template_steps:
            current_db_step = db_steps[t_step['id']]
            for dep_template_id in t_step.get('dependencies', []):
                # Fetch corresponding database step that this step depends on
                dep_db_step = db_steps.get(dep_template_id)
                if dep_db_step:
                    dependency_link = StepDependency(
                        step_id=current_db_step.id,
                        depends_on_step_id=dep_db_step.id
                    )
                    db.session.add(dependency_link)
        
        try:
            db.session.commit()
            logger.info(f"Successfully planned administrative journey for goal: '{goal_text}'")
            return journey
        except Exception as e:
            db.session.rollback()
            logger.error(f"Failed to persist journey plan: {e}")
            raise e

    @staticmethod
    def get_journey_analysis(journey_id):
        """
        Retrieves the complete state details of the journey, including:
        - Journey details & DAG steps
        - Journey Health (progress metrics)
        - Next Best Action (the next executable steps)
        """
        journey = Journey.query.get(journey_id)
        if not journey:
            return None
            
        steps = journey.steps
        total_steps = len(steps)
        
        if total_steps == 0:
            return {
                'journey': journey.to_dict(),
                'health': {'progress_percentage': 0},
                'next_best_action': None
            }
            
        # Calculate health metrics
        completed_steps = sum(1 for s in steps if s.status == 'COMPLETED')
        progress_percentage = int((completed_steps / total_steps) * 100)
        
        # Find next best actions (steps that are currently PENDING)
        pending_steps = [s.to_dict() for s in sorted(steps, key=lambda s: s.sequence_order) if s.status == 'PENDING']
        
        # Journey Health status assessment
        health_status = "healthy"
        if progress_percentage < 100 and len(pending_steps) == 0:
            # Graph is stalled: not all steps completed, but no pending steps are unlocked (potential deadlock / user action required)
            health_status = "stalled"
            
        analysis = {
            'journey': journey.to_dict(),
            'health': {
                'total_steps': total_steps,
                'completed_steps': completed_steps,
                'progress_percentage': progress_percentage,
                'status': health_status
            },
            'next_best_action': pending_steps[0] if len(pending_steps) > 0 else None
        }
        
        return analysis

    @staticmethod
    def complete_step(journey_id, step_id):
        """
        Marks a step as COMPLETED and recursively unlocks downstream steps in the DAG
        whose dependencies are now fully satisfied.
        """
        step = JourneyStep.query.filter_by(journey_id=journey_id, id=step_id).first()
        if not step:
            raise ValueError(f"Step {step_id} not found in journey {journey_id}")
            
        if step.status == 'COMPLETED':
            return Journey.query.get(journey_id)
            
        step.status = 'COMPLETED'
        db.session.add(step)
        
        # Find downstream steps that depend on this step
        # By searching StepDependency where depends_on_step_id is our completed step
        blocked_dependencies = StepDependency.query.filter_by(depends_on_step_id=step.id).all()
        
        for dep in blocked_dependencies:
            downstream_step = JourneyStep.query.get(dep.step_id)
            if downstream_step and downstream_step.status == 'LOCKED':
                # Check if all other prerequisites for this downstream step are completed
                prereqs = StepDependency.query.filter_by(step_id=downstream_step.id).all()
                all_prereqs_completed = True
                
                for prereq in prereqs:
                    prereq_step = JourneyStep.query.get(prereq.depends_on_step_id)
                    if prereq_step and prereq_step.status != 'COMPLETED':
                        all_prereqs_completed = False
                        break
                        
                if all_prereqs_completed:
                    downstream_step.status = 'PENDING'
                    db.session.add(downstream_step)
                    
        try:
            db.session.commit()
            
            # Recalculate and update overall journey status if all steps are completed
            journey = Journey.query.get(journey_id)
            all_steps_completed = all(s.status == 'COMPLETED' for s in journey.steps)
            if all_steps_completed:
                journey.status = 'COMPLETED'
                db.session.add(journey)
                db.session.commit()
                
            return journey
        except Exception as e:
            db.session.rollback()
            logger.error(f"Failed to update step completion: {e}")
            raise e
